version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'

  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manage-contact-list-wt

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/manage-contact-list-wt
    volumes:
      - /app/node_modules
      - ./server:/app
    links:
      - postgres
    ports:
      - '5001:4000'
    depends_on:
      - postgres

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:80'
    volumes:
      - /app/node_modules
      - ./client:/app
    links:
      - api
